language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y g++-4.8
  - sudo apt-get install -y libssl-dev
  - sudo apt-get install -y libz-dev
  - sudo apt-get install -y libsqlite3-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90

script:
  - $CXX --version
  - python configure.py $BUILD_MODE --cpu=$CPU --cc=$CC --cc-abi-flags=$CC_ABI_FLAGS --cc-bin=$CXX --with-openssl --with-sqlite --with-zlib
  - "make"
  - "LD_LIBRARY_PATH=. ./botan-test"

notifications:
  email: lloyd@randombit.net

os:
  - linux

env:
  - CPU="x86_64" BUILD_MODE=""
  - CPU="x86_64" BUILD_MODE="--via-amalgamation --disable-shared"
  - CPU="x86_32" CC_ABI_FLAGS="-m32" BUILD_MODE=""
  - CPU="x86_32" CC_ABI_FLAGS="-m32" BUILD_MODE="--via-amalgamation --disable-shared"
