language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  matrix:
    - BUILD_MODE="shared"
    - BUILD_MODE="static"
    - BUILD_MODE="coverage"

matrix:
  exclude:
    - os: osx
      compiler: gcc
    - compiler: clang
      env: BUILD_MODE="coverage"

sudo: required

install:
  - ./src/scripts/ci/setup.sh

script:
  - ./src/scripts/ci/build.sh

after_success:
  - ./src/scripts/ci/after_success.sh

notifications:
  email: lloyd@randombit.net

addons:
  coverity_scan:
    project:
      name: "randombit/botan"
    notification_email: lloyd@randombit.net
    build_command_prepend: "./configure.py"
    build_command: "make -j4"
    branch_pattern: coverity_scan
