language: cpp

os:
  - linux

compiler:
  - clang
  - gcc

env:
  - BUILD_MODE="shared"
  - BUILD_MODE="static"
  - BUILD_MODE="coverage"

  global:
    # Coverity token
    - secure: "g5vrCKeJwv+Brjlf1yuv/3FsJBVF9jVB+TmIyzXqTVzUk2LLFMNax04LaMTrQKHVrkXX/r/XdiTIl8/9EMqQGDx/kAPZpde5uJqy1aV8fE2IvYRj7sNSRm2smKNaioZnFYH6sm8dthoDARjxBY/nPmop0F6LVqSyRdZZVT9I/QY="


matrix:
  exclude:
    - compiler: clang
      env: BUILD_MODE="coverage"

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - ./src/scripts/ci/setup.sh

script:
  - ./src/scripts/ci/build.sh

after_success:
  - ./src/scripts/ci/after_success.sh

notifications:
  email: lloyd@randombit.net

addons:
  coverity_scan:
    project:
      name: "randombit/botan"
      description: "Build submitted via Travis CI"
    notification_email: lloyd@randombit.net
    build_command_prepend: "./configure.py"
    build_command: "make -j 4"
    branch_pattern: master
