os: Visual Studio 2015

platform:
  - x86
  - x86_amd64

environment:
  matrix:
    - COMPILER: msvc-14.0
    - COMPILER: msvc-12.0
    - MODE: --enable-shared
    - MODE: --disable-shared

install:
  - if %compiler% == msvc-12.0 (
       call "%ProgramFiles(x86)%\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %PLATFORM%
    )
  - if %compiler% == msvc-14.0 (
       call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %PLATFORM%
    )
  - cl # check compiler version

# always build via amalgamation due to build time constraints on appveyor
build_script:
  - python configure.py --cc=msvc --via-amalgamation --cpu=%PLATFORM% %MODE%
  - nmake
  - botan-test
  - nmake install
