language: cpp

dist: xenial
sudo: required

env:
  global:
    - CCACHE_MAXSIZE=1G

jobs:
  include:
    - os: linux
      name: Linux/GCC
      compiler: gcc
      env:
       - TARGET="shared"

    - os: linux
      name: Linux/Clang
      compiler: clang
      env:
       - TARGET="shared"

    - os: linux
      name: Coverage
      compiler: gcc
      env:
       - TARGET="coverage"

    - os: linux
      name: Fuzzers
      compiler: gcc
      env:
       - TARGET="fuzzers"

    - os: linux
      name: Valgrind
      compiler: gcc
      env:
       - TARGET="valgrind"

    - os: linux
      name: Linux arm64
      arch: arm64
      compiler: gcc
      env:
       - TARGET="shared"

    - os: linux
      dist: bionic
      name: Linux ppc64le
      arch: ppc64le
      compiler: gcc
      env:
       - TARGET="shared"

    - os: linux
      name: Linux i386 cross
      compiler: gcc
      env:
       - TARGET="cross-i386"

    - os: linux
      name: Linux ppc32 cross
      compiler: gcc
      env:
       - TARGET="cross-ppc32"

    - os: linux
      name: Linux arm32 cross
      compiler: gcc
      env:
       - TARGET="cross-arm32"

    - os: linux
      name: Linux mips64 cross
      compiler: gcc
      env:
       - TARGET="cross-mips64"

    - os: linux
      name: Android arm32 cross
      compiler: clang
      env:
       - TARGET="cross-android-arm32"
       - ANDROID_NDK=android-ndk-r20

    - os: linux
      name: Android arm64 cross
      compiler: clang
      env:
       - TARGET="cross-android-arm64"
       - ANDROID_NDK=android-ndk-r20

    - os: linux
      name: MinGW x86-64 cross
      compiler: gcc
      env:
       - TARGET="cross-win64"

    - os: osx
      name: macOS
      compiler: clang
      env:
       - TARGET="shared"

    - os: osx
      name: iOS
      compiler: clang
      env:
       - TARGET="cross-arm64"

    - os: linux
      name: Linux GCC 4.8
      compiler: gcc
      env:
       - TARGET="gcc4.8"

    - os: linux
      name: Minimized
      compiler: gcc
      env:
       - TARGET="mini-shared"

    - os: linux
      name: BSI policy
      compiler: gcc
      env:
       - TARGET="bsi"

    - os: linux
      name: NIST policy
      compiler: gcc
      env:
       - TARGET="nist"

    - os: linux
      name: Pylint
      compiler: gcc
      env:
       - TARGET="lint"

    - os: linux
      name: Documentation
      compiler: gcc
      env:
       - TARGET="docs"

install:
  - ./src/scripts/ci/setup_travis.sh

script:
  - ./src/scripts/ci_build.py --os=$TRAVIS_OS_NAME --cc=$CC --cc-bin=$CXX --without-pylint3 --pkcs11-lib=/usr/lib/softhsm/libsofthsm2.so $TARGET

# whitelist branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
    - master
    - release-2
    - coverity_scan

git:
  depth: 10

cache:
  ccache: true

addons:
  coverity_scan:
    project:
      name: "randombit/botan"
    notification_email: jack@randombit.net
    build_command_prepend: "./configure.py --no-optimizations --with-zlib --with-openssl"
    build_command: "make -j2"
    branch_pattern: coverity_scan
